config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'homes#index'

  resources :merchants, only: [:index, :show]

  devise_for :users
  devise_for :merchants
  devise_for :admins
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < User
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/merchant.rb
# frozen_string_literal: true

class Merchant < User
  has_many :transactions, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
end

app/models/transaction.rb
# frozen_string_literal: true

class User < ApplicationRecord
  belongs_to :merchant

  validates :amount, presence: true
  validates :status, presence: true
  validates :customer_email, presence: true
  validates :customer_phone, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  devise_group :user, contains: [:admin, :merchant, :user]
  before_action :authenticate_user!
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def index; end
end

app/controllers/merchants_controller.rb
# frozen_string_literal: true

class MerchantsController < ApplicationController
  before_action :set_merchant, only: %i[show destroy]

  def index
    @merchants = Merchant.all
  end

  def show; end

  def destroy
    @merchant.destroy

    redirect_to merchants_url, notice: 'Merchant was successfully destroyed.'
  end

  private

  def set_merchant
    @merchant = Merchant.find(params[:id])
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show destroy]

  def index
    @transactions = current_user.transactions.all
  end

  def show; end

  def destroy
    @transaction.destroy

    redirect_to transactions_url, notice: 'Transaction was successfully destroyed.'
  end

  private

  def set_transaction
    @merchant = Transaction.find(params[:id])
  end
end

app/controllers/users/devise_controller.rb
# frozen_string_literal: true

module Users
  class DeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => e
        if get?
          raise e
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice'
      'alert-success'
    when 'alert'
      'alert-warning'
    when 'error'
      'alert-danger'
    end
  end

  def admin?(object)
    object.type == 'Admin'
  end
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/views/homes/index.html.slim
section.home-index
  .py-4
    .p-5.mb-4.bg-light.rounded-3
      .container-fluid.py-5
        h1.display-5.fw-bold Custom jumbotron
        p.col-md-8.fs-4 Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.
        button.btn.btn-primary.btn-lg type="button"  Example button
    .row.align-items-md-stretch
      .col-md-6
        .h-100.p-5.text-bg-dark.rounded-3
          h2 Change the background
          p Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.
          button.btn.btn-outline-light type="button"  Example button
      .col-md-6
        .h-100.p-5.bg-light.border.rounded-3
          h2 Add borders
          p Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.
          button.btn.btn-outline-secondary type="button"  Example button

app/views/layouts/application.html.slim
doctype html
html
  head
    title Payment
    meta content="width=device-width,initial-scale=1" name="viewport"
    = csrf_meta_tags
    = csp_meta_tag
    
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  body
    = render 'shared/header'
    main.container
      #flash
        = render 'shared/flash'
      = yield
    = render 'shared/footer'

app/views/merchants/_merchant.html.slim
div id="#{dom_id merchant}"
  p
    = merchant.email

app/views/merchants/index.html.slim
h1 Merchants

#merchants
  - @merchants.each do |merchant|
    = render merchant
    p
      = link_to "Show this merchant", merchant

    -if admin?(current_user)
      = link_to "New merchant", new_merchant_path, class: 'btn-outline-primary'

app/views/merchants/show.html.slim
p = @merchant.name
p = @merchant.description
p = @merchant.email

div
  = link_to "Back to merchants", merchants_path

-if admin?(current_user)
  = button_to "Destroy this merchant", @merchant, method: :delete, class: '.btn-outline-danger'

app/views/shared/_errors.html.slim
- if object&.errors&.full_messages&.any?
  .alert alert-danger
    ul
      - object.errors.full_messages.each do |msg|
        li
          = msg

app/views/shared/_flash.html.slim
- flash.each do |k, v|
  = tag.div v, class: "alert #{flash_class(k)}", role: 'alert'

app/views/shared/_footer.html.slim
footer.py-5.text-bg-dark
  .container
    .row
      .col-6.col-md-2.mb-3
        h5 Section
        ul.nav.flex-column
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  Home
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  Features
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  Pricing
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  FAQs
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  About
      .col-6.col-md-2.mb-3
        h5 Section
        ul.nav.flex-column
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  Home
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  Features
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  Pricing
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  FAQs
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  About
      .col-6.col-md-2.mb-3
        h5 Section
        ul.nav.flex-column
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  Home
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  Features
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  Pricing
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  FAQs
          li.nav-item.mb-2
            a.nav-link.p-0.text-muted href="#"  About
      .col-md-5.offset-md-1.mb-3
        form
          h5 Subscribe to our newsletter
          p Monthly digest of what's new and exciting from us.
          .d-flex.flex-column.flex-sm-row.w-100.gap-2
            label.visually-hidden for="newsletter1"  Email address
            input#newsletter1.form-control placeholder=("Email address") type="text" /
            button.btn.btn-primary type="button"  Subscribe
    .d-flex.flex-column.flex-sm-row.justify-content-between.py-4.my-4.border-top
      p &copy; 2022 Company, Inc. All rights reserved.
      ul.list-unstyled.d-flex
        li.ms-3
          a.link-dark href="#" 
            svg.bi height="24" width="24" 
              use xlink:href="#twitter" /
        li.ms-3
          a.link-dark href="#" 
            svg.bi height="24" width="24" 
              use xlink:href="#instagram" /
        li.ms-3
          a.link-dark href="#" 
            svg.bi height="24" width="24" 
              use xlink:href="#facebook" /

app/views/shared/_header.html.erb
<header class="p-3 text-bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <%= image_tag 'logo-white.png', title: "Logo Payment", alt: "Payment Logo", class: "bi me-2", heght: "32", width: "40" %>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><%= link_to 'Home', root_path, class: 'nav-link px-2 text-secondary' %></li>
        <li><%= link_to 'Merchants', merchants_path, class: 'nav-link px-2 text-white' %></li>
      </ul>

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
        <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
      </form>

      <div class="text-end">
        <% if merchant_signed_in? %>
          <div class="dropdown">
            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
            </a>
            <ul class="dropdown-menu text-small">
              <li><%= link_to 'Settings', edit_merchant_registration_path, class: 'dropdown-item' %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= button_to 'Sign out', destroy_merchant_session_path, method: :delete, data: { confirm: 'Are you sure?' }, title: "Sign out", alt: "Logout", class: "dropdown-item" %></li>
            </ul>
          </div>
        <% elsif admin_signed_in? %>
          <div class="dropdown">
            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
            </a>
            <ul class="dropdown-menu text-small">
              <li><%= link_to 'Settings', edit_admin_registration_path, class: 'dropdown-item' %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= button_to 'Sign out', destroy_admin_session_path, method: :delete, data: { confirm: 'Are you sure?' }, title: "Sign out", alt: "Logout", class: "dropdown-item" %></li>
            </ul>
          </div>
        <% elsif user_signed_in? %>
          <div class="dropdown">
            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
            </a>
            <ul class="dropdown-menu text-small">
              <li><%= link_to 'Settings', edit_user_registration_path, class: 'dropdown-item' %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= button_to 'Sign out', destroy_admin_session_path, method: :delete, data: { confirm: 'Are you sure?' }, title: "Sign out", alt: "Logout", class: "dropdown-item" %></li>
            </ul>
          </div>
        <% else %>
          <%= link_to 'Sign in', new_user_session_path, class: "btn btn-outline-light me-2" %>
          <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-warning" %>
        <% end %>
      </div>
    </div>
  </div>
</header>